export interface ResponseMeta { requestId: string; timestamp: string; version: string; sourceWarning?: string; }
export interface ApiEnvelope<T> { ok: boolean; meta: ResponseMeta; data?: T; error?: { code: string; message: string; details?: Record<string, unknown>; }; }
export interface HomeHero { totalEquity: number; totalInvested: number; totalProfitLoss: number; totalProfitLossPct: number; statusLabel: string; }
export interface PrimaryProblem { code: string; title: string; body: string; severity: string; }
export interface PrimaryAction { code: string; title: string; body: string; ctaLabel: string; target: string; }
export interface ScoreData { value: number; status: string; explanation: string; }
export interface DistributionItem { key: string; label: string; value: number; sharePct: number; performancePct: number; sourceType: string; }
export interface InsightItem { kind: string; title: string; body: string; }
export interface AiSuggestion { status: 'disabled' | 'ready' | 'error'; text?: string; provider?: string; generatedAt?: string; message?: string; }
export interface HomeData { screenState: 'redirect_onboarding' | 'empty' | 'portfolio_ready_analysis_pending' | 'ready'; redirectTo?: string; portfolioId: string; hero: HomeHero; primaryProblem: PrimaryProblem; primaryAction: PrimaryAction; score: ScoreData; distribution: DistributionItem[]; insights: InsightItem[]; aiSuggestion?: AiSuggestion; updatedAt: string; }
export interface PortfolioSummary { totalEquity: number; totalInvested: number; totalProfitLoss: number; totalProfitLossPct: number; statusLabel: string; }
export interface PortfolioHoldingListItem { id: string; assetId: string; code: string; name: string; categoryKey: string; categoryLabel: string; platformId: string; platformName: string; quantity: number; averagePrice: number; currentPrice: number | null; currentValue: number; investedAmount: number; performanceValue: number; performancePct: number | null; allocationPct: number; quotationStatus: 'priced' | 'missing_quote'; }
export interface PortfolioGroup { categoryKey: string; categoryLabel: string; totalInvested: number; totalCurrent: number; totalProfitLoss: number; totalProfitLossPct: number | null; holdings: PortfolioHoldingListItem[]; }
export interface PortfolioEmptyState { title: string; body: string; ctaLabel: string; target: string; }
export interface PortfolioData { screenState: 'redirect_onboarding' | 'empty' | 'ready'; redirectTo?: string; portfolioId: string; summary: PortfolioSummary; emptyState?: PortfolioEmptyState; groups: PortfolioGroup[]; filters: { performance: 'all' | 'best' | 'worst' }; orders: Array<never>; }
export interface HoldingDetailData { screenState?: 'redirect_onboarding'; redirectTo?: string; holding: { id: string; assetId: string; code: string; name: string; categoryKey: string; categoryLabel: string; platformId: string; platformName: string; quantity: number; averagePrice: number; currentPrice: number | null; currentValue: number; investedAmount: number; performanceValue: number; performancePct: number | null; allocationPct: number; recommendation: string; statusLabel: string; quotationStatus: 'priced' | 'missing_quote'; notes: string; stopLoss: number | null; targetPrice: number | null; sourceKind: string; assetTypeCode: string; }; ranking: { score: number; status: string; motives: string[]; opportunityScore: number; }; recommendation: { code: string; title: string; body: string; }; categoryContext: { categoryKey: string; categoryLabel: string; categoryRisk: string; categoryRecommendation: string; primaryMessage: string; holdingsCount: number; totalCurrent: number; totalInvested: number; totalProfitLoss: number; totalProfitLossPct: number | null; }; externalLink: string; benchmarkComparison?: { benchmark: 'CDI'; fromDate: string; toDate: string; benchmarkAccumulatedPct: number | null; holdingPerformancePct: number | null; deltaPct: number | null; status: 'disabled' | 'degraded' | 'ok'; label: string; } | null; }
export interface HistorySnapshotItem { id: string; referenceDate: string; totalEquity: number; totalInvested: number; totalProfitLoss: number; totalProfitLossPct: number; createdAt: string; analysisBadge: { status: string; primaryProblem: string; primaryAction: string; } | null; }
export interface HistoryData { screenState: 'redirect_onboarding' | 'empty' | 'ready'; redirectTo?: string; portfolioId: string; emptyState?: { title: string; body: string; ctaLabel: string; target: string; }; summary: { totalSnapshots: number; latestReferenceDate: string | null; }; snapshots: HistorySnapshotItem[]; }
export interface AnalysisData { screenState: 'redirect_onboarding' | 'pending' | 'ready'; redirectTo?: string; portfolioId?: string; analysisId?: string; snapshotId?: string; pendingState?: { title: string; body: string; ctaLabel: string; target: string; }; score?: { value: number; status: string; explanation: string; }; primaryProblem?: { code: string; title: string; body: string; severity: string; }; primaryAction?: { code: string; title: string; body: string; ctaLabel: string; target: string; }; portfolioDecision?: string; actionPlan?: string[]; summary?: string; insights?: Array<{ kind: string; title: string; body: string; priority: number; }>; generatedAt?: string; }
export interface PortfolioEntryOnboardingData { screenState: 'profile_context_required' | 'resume_pending_import' | 'portfolio_already_started' | 'entry_ready'; redirectTo?: string; portfolioId?: string; title: string; body: string; primaryAction: { code: string; title: string; target: string; }; secondaryAction?: { code: string; title: string; target: string; }; recommendation?: { methodCode: string; title: string; reason: string; target: string; }; methods: Array<{ code: string; title: string; body: string; target: string; recommended: boolean; availability: string; }>; metrics?: { activePositions: number; pendingImports: number; completedImports: number; declaredPlatforms: number; hasKnownBrokerContext: boolean; }; }
export interface ImportStartData { importId: string; status: string; nextStep: string; totals: { totalRows: number; validRows: number; invalidRows: number; duplicateRows: number; }; document?: Record<string, unknown> | null; importable?: boolean; }
export interface ImportPreviewData { importId: string; status: string; origin: string; totals: { totalRows: number; validRows: number; invalidRows: number; duplicateRows: number; }; readyToCommit: boolean; document?: Record<string, unknown> | null; importable?: boolean; rows: Array<{ id: string; rowNumber: number; source: Record<string, unknown>; normalized: Record<string, unknown>; resolutionStatus: string; errorMessage: string | null; fieldSources?: Record<string, unknown>; fieldConfidences?: Record<string, unknown>; warnings?: string[]; reviewMeta?: Record<string, unknown>; }>; }
export interface ImportEngineStatusData { screenState: 'ready' | 'redirect_onboarding'; redirectTo?: string; importId: string; origin: string; importStatus: string; engineStatus: { code: 'recebido' | 'processando' | 'concluido' | 'baixa_confianca' | 'fallback' | 'nao_importavel' | 'pronto_para_revisao'; label: string; body: string; readyForReview: boolean; readyToCommit: boolean; }; document: { parserMode: string | null; confidence: number | null; importable: boolean; }; summary: { totalRows: number; processedRows: number; validRows: number; invalidRows: number; duplicateRows: number; lowConfidenceRows: number; blockedRows: number; failedRows: number; fallbackRows: number; manualDecisionRows: number; aiAssistedRows: number; }; states: { received: boolean; processing: boolean; completed: boolean; lowConfidence: boolean; fallback: boolean; nonImportable: boolean; readyForReview: boolean; }; targets: { preview: string; detail: string; conflicts: string | null; commit: string | null; }; }
export interface ImportDetailData { screenState: 'ready' | 'redirect_onboarding'; redirectTo?: string; importId: string; importMeta: { origin: string; originLabel: string; status: string; statusLabel: string; totalRows: number; validRows: number; invalidRows: number; duplicateRows: number; createdAt?: string | null; updatedAt?: string | null; finishedAt?: string | null; fileName?: string | null; mimeType?: string | null; }; operationalSummary: { engineStatus: { code: 'recebido' | 'processando' | 'concluido' | 'baixa_confianca' | 'fallback' | 'nao_importavel' | 'pronto_para_revisao'; label: string; body: string; readyForReview: boolean; readyToCommit: boolean; }; document: { fileName: string | null; mimeType: string | null; documentType: string | null; parserMode: string | null; confidence: number | null; importable: boolean; }; counts: { totalRows: number; validRows: number; invalidRows: number; duplicateRows: number; lowConfidenceRows: number; blockedRows: number; failedRows: number; fallbackRows: number; manualDecisionRows: number; }; targets: { engineStatus: string; preview: string; conflicts: string | null; }; }; issueSummary: { errorRows: number; conflictRows: number; lowConfidenceRows: number; nonImportableRows: number; items: Array<{ rowId: string; rowNumber: number; resolutionStatus: string; errorMessage: string | null; issueKinds: string[]; }>; }; decisionSummary: { manualRows: number; fallbackRows: number; aiRows: number; systemRows: number; items: Array<{ rowId: string; rowNumber: number; code: string; label: string; origin: 'manual' | 'fallback' | 'ia' | 'system'; details: string; }>; }; snapshot: { id: string; referenceDate: string; totalEquity: number; totalInvested: number; totalProfitLoss: number; totalProfitLossPct: number; target: string; } | null; rows: Array<{ rowId: string; rowNumber: number; resolutionStatus: string; errorMessage: string | null; source: Record<string, unknown>; normalized: { sourceKind: string; code: string; name: string; normalizedName: string; quantity: number; investedAmount: number; currentAmount: number; averagePrice: number | null; currentPrice: number | null; categoryLabel: string; notes: string; }; fieldSources: Record<string, unknown>; fieldConfidences: Record<string, unknown>; lowConfidenceFields: Array<{ field: string; confidence: number; source: string; }>; warnings: string[]; reviewMeta: Record<string, unknown>; documentMeta: Record<string, unknown> | null; duplicateCandidates: unknown[]; operationalFlags: { hasError: boolean; hasConflict: boolean; hasLowConfidence: boolean; usedFallback: boolean; usedAi: boolean; usedManualDecision: boolean; nonImportable: boolean; }; decision: { code: string; label: string; origin: 'manual' | 'fallback' | 'ia' | 'system'; details: string; }; }>; }
export interface ImportConflictData { screenState: 'empty' | 'ready' | 'redirect_onboarding'; redirectTo?: string; importId: string; origin: string; summary: { totalConflicts: number; unresolvedConflicts: number; resolvedConflicts: number; }; emptyState?: { title: string; body: string; ctaLabel: string; target: string; }; conflicts: Array<{ rowId: string; rowNumber: number; resolutionStatus: string; errorMessage: string | null; incoming: { sourceKind: string; code: string; name: string; quantity: number; investedAmount: number; currentAmount: number; categoryLabel: string; }; duplicateCandidates: Array<{ assetId: string; assetCode: string; assetName: string; quantity: number; investedAmount: number; currentAmount: number; }>; allowedActions: Array<{ code: 'keep_current' | 'replace_existing' | 'consolidate' | 'ignore_import'; label: string; }>; target: { preview: string; resolve: string; }; }>; }
export interface ImportCommitData { importId: string; status: string; createdSnapshotId: string; affectedPositions: number; nextStep: string; }
export interface ImportTemplateDownloadData { kind: 'CSV_V1'; fileName: string; contentType: string; }
